apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hello-camel-k
spec:
  sources:
  - name: HelloCamelK.java
    content: |
      // camel-k: language=java

      import org.apache.camel.builder.RouteBuilder;

      public class HelloCamelK extends RouteBuilder {
        @Override
        public void configure() throws Exception {

            // Write your routes here, for example:
            from("timer:java?period=1000")
              .routeId("java")
              .setBody()
                .simple("Hello Camel K from ${routeId}")
              .to("log:info");

        }
      }
